loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  storage_config:
    filesystem:
      directory: /data/loki/chunks
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_entries_limit_per_query: 5000
  useTestSchema: true

# Use single binary mode
singleBinary:
  replicas: 1

# Disable simple scalable mode
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

persistence:
  enabled: true
  size: 10Gi

serviceMonitor:
  enabled: true
